//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugLogger.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Bug
    {
        public int Id { get; set; }

        [Required]
        public string Text { get; set; }

        public DateTime LogDate { get; set; }

        public int Status_Id { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
