//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugLogger.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Bugs = new HashSet<Bug>();
        }
    
        public int Id { get; set; }

        public string State { get; set; }
    
        public virtual ICollection<Bug> Bugs { get; set; }
    }
}
