# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'try2' do
pod 'Parse', '~> 1.4' 
pod 'Google-Maps-iOS-SDK', '~> 1.7.2'
end

target 'try2Tests' do

end

